FROM python:3.12.11-slim-bookworm
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PYTHONPATH=/work
WORKDIR /work
COPY requirements-dev.txt requirements.txt /work/
RUN python -m pip install --no-cache-dir --requirement /work/requirements-dev.txt
COPY app /work/app
COPY tests /work/tests
COPY pyproject.toml /work/pyproject.toml
ENTRYPOINT ["pytest", "-q"]
